language: python
os:
  - linux

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run py.test -vs -n 4 tests --cov

after_success:
  - pipenv run codecov

notifications:
  email: false

deploy:
  provider: pypi
  user: overcat_build_bot
  password:
    secure: d26j1x65KB4TwXh0a/pPxU2P/KmlDdIdXoc5v/AEe+lOL/YfBDDCoBmp9GGyR7EGPhd1SmZlMeHQ6mCbCzBta8eSfbzcjWv6rREZrQIjiCJB2z+HJVHXBGD6dZ5UGozrHqotL395r8a3sAM0k/22fBed1lHDbFLvyyDo7yIeEp3Ua1oyB2rx8TF8/jl3sGD2v+Zv7t5x+uvspZ7gshx0ODmwdK9jttiRdrHHiVxFtVcU2QQlbTzNHSOd1Ff+vxb7vamcHjsMdLIwg1lkjDcruRclYJAJ2Vyl/JwKkkxk55D8qXP3N5u71yMeD/Z7OKE4k2oOf7/Qch0JvbWQT0IYdV54pBGze65WhSt7On+qRnD/qMsJ+lEMx32ol1k0gefXNQcaunGum+cjxyltxr8A8+e06WgYcl2AzQfcK0V/J2dy/1OLwOqnEDFt8peadaXoxD0nIDN4QN64uoWbQuF92W/O8f93nyYlAbsexXr06FPBZsfXzVgKz2pM3uHgtltFyRYWvURQ6PZ1Bioiz9batAPHXgGtoMUTo+OtaLdnknsMeKe62+q9DVln+tzRczrFK2NS2cmHw63unc69qUpv5gYioVoEGZWZg0ACCbYgmQu7B9aQfVD/QfshWT8bfrqa2Eiye68MLSdvCi27UMWVfjTpSn2fZ+L+LXfNX5ZyQk8=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    tags: true
