language: python
os:
  - linux

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run py.test -vs -n 4 tests --cov

notifications:
  email: false

deploy:
  provider: pypi
  user: overcat_build_bot
  password:
    secure: Iw+1oY1M1Bda+j3s0K87zkqdfiU8OqgxLmdsHW4MffpOXdtDSGPqQei0jQen/OKg8laoOId2pJmBye5OHO+cvniT4KI6alAixfqTQkykL6JRdzmsbchCPXnGYox8CjrYd0ABMtrEqfUIW2XzZIslSE7j7nVLzzVdPnmemKyfOQVLCEL3pSTUdGkrfE3/Dh1rp8y7oEKWeq39VHwSBvMSNpFLfDnO0OTxnEAO+FZPgFLpA6tphe5aVcwbUJOc86Cs9JmLuJb6hkyXRSvuRyTz65o5KCUsRwG32nRq1LvV3WAU1UjtHCsqsm0ZoLg/qVqjvOc+Y73O+Gbv8QoE+ihrQshIniNVJMz7He6sNH0cr7oZGsNkzn13+mys7MqgaG6UustdfyqzUhXglFYlZSrprg+jRt5UiVywYobtE09zX40PFtal9EMws40SCTReg+D0ogQgHy6Zp0UGDhYgTJECFsb76UJE2xL1Uq9LVD73fWtTZxY83ZSOrWY4wBnp5SEdNexiLH5LyvgKJiBGe6yD6Rd22gtvI9J8ymsEvub7Lf+PU/niGYjotkOvSLskbQLKIq/38Dgn4847M/OInrNDvMTN/rin2ubDEPF0jrr9N6W6gPXxYqthmK/giNMeYtQ9tVYG5OGVawAm7/2U7Lm5dPxSE88wyFUIPNdwDis2dgo=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    tags: true
