language: python
os:
  - linux

python:
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run py.test -vs -n 4 tests --cov

notifications:
  email: false