# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from fank import cma9_pb2 as fank_dot_cma9__pb2


class Cma9ServiceStub(object):
  """//////////////////////////////////////////////////////////////////////////////////////////////////
  CMA-9 Service REST API.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAccountRequest = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/CreateAccountRequest',
        request_serializer=fank_dot_cma9__pb2.AccountRequestsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.AccountRequestsResponse.FromString,
        )
    self.RemoveAccountRequest = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/RemoveAccountRequest',
        request_serializer=fank_dot_cma9__pb2.DeleteAccountRequestsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.DeleteAccountRequestsResponse.FromString,
        )
    self.GetAccounts = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/GetAccounts',
        request_serializer=fank_dot_cma9__pb2.AccountsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.AccountsResponse.FromString,
        )
    self.GetAccount = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/GetAccount',
        request_serializer=fank_dot_cma9__pb2.AccountRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.AccountResponse.FromString,
        )
    self.GetAccountBalances = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/GetAccountBalances',
        request_serializer=fank_dot_cma9__pb2.AccountBalancesRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.AccountBalancesResponse.FromString,
        )
    self.GetAccountTransactions = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/GetAccountTransactions',
        request_serializer=fank_dot_cma9__pb2.AccountTransactionsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.AccountTransactionsResponse.FromString,
        )
    self.CreatePayment = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/CreatePayment',
        request_serializer=fank_dot_cma9__pb2.PaymentsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.PaymentsResponse.FromString,
        )
    self.CreatePaymentSubmission = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/CreatePaymentSubmission',
        request_serializer=fank_dot_cma9__pb2.PaymentSubmissionsRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.PaymentSubmissionsResponse.FromString,
        )
    self.GetParty = channel.unary_unary(
        '/io.token.proto.cma9.Cma9Service/GetParty',
        request_serializer=fank_dot_cma9__pb2.PartyRequest.SerializeToString,
        response_deserializer=fank_dot_cma9__pb2.PartyResponse.FromString,
        )


class Cma9ServiceServicer(object):
  """//////////////////////////////////////////////////////////////////////////////////////////////////
  CMA-9 Service REST API.

  """

  def CreateAccountRequest(self, request, context):
    """Used to request information about accounts and transactions.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveAccountRequest(self, request, context):
    """Used to delete a request for account/transaction information.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccounts(self, request, context):
    """Used to retrieve a list of accounts the AISP is authorized to access
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccount(self, request, context):
    """Used to query information about a particular account.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountBalances(self, request, context):
    """Used to query account balances.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountTransactions(self, request, context):
    """Used to query information about an account's transactions.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePayment(self, request, context):
    """Used to create a payment object, later to be redeemed.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePaymentSubmission(self, request, context):
    """Used to submit/redeem an existing payment object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetParty(self, request, context):
    """Used to get account details
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Cma9ServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAccountRequest': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAccountRequest,
          request_deserializer=fank_dot_cma9__pb2.AccountRequestsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.AccountRequestsResponse.SerializeToString,
      ),
      'RemoveAccountRequest': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveAccountRequest,
          request_deserializer=fank_dot_cma9__pb2.DeleteAccountRequestsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.DeleteAccountRequestsResponse.SerializeToString,
      ),
      'GetAccounts': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccounts,
          request_deserializer=fank_dot_cma9__pb2.AccountsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.AccountsResponse.SerializeToString,
      ),
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=fank_dot_cma9__pb2.AccountRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.AccountResponse.SerializeToString,
      ),
      'GetAccountBalances': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountBalances,
          request_deserializer=fank_dot_cma9__pb2.AccountBalancesRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.AccountBalancesResponse.SerializeToString,
      ),
      'GetAccountTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountTransactions,
          request_deserializer=fank_dot_cma9__pb2.AccountTransactionsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.AccountTransactionsResponse.SerializeToString,
      ),
      'CreatePayment': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePayment,
          request_deserializer=fank_dot_cma9__pb2.PaymentsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.PaymentsResponse.SerializeToString,
      ),
      'CreatePaymentSubmission': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePaymentSubmission,
          request_deserializer=fank_dot_cma9__pb2.PaymentSubmissionsRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.PaymentSubmissionsResponse.SerializeToString,
      ),
      'GetParty': grpc.unary_unary_rpc_method_handler(
          servicer.GetParty,
          request_deserializer=fank_dot_cma9__pb2.PartyRequest.FromString,
          response_serializer=fank_dot_cma9__pb2.PartyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.token.proto.cma9.Cma9Service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
